**Exercício 1: Estatísticas Descritivas**

Crie um array de 50 números inteiros aleatórios entre 1 e 100. Calcule e exiba a média, mediana, desvio padrão, valor máximo e valor mínimo.

In [11]:
import numpy as np 

np.random.seed(2)
base = np.random.randint(1,101,50)

print(f'{base}\n')
print(f"Média: {np.mean(base)}")
print(f"Mediana: {np.median(base)}")
print(f"Desvio Padrão: {np.std(base):.2f}")
print(f"Máximo: {np.max(base)}")
print(f"Mínimo: {np.min(base)}")

[41 16 73 23 44 83 76  8 35 50 96 76 86 48 64 32 91 21 38 40 68  5 43 52
 39 34 59 68 70 89 69 47 71 96 84 32 67 81 53 77 51  5 91 64 80 50 40 47
  9 51]

Média: 54.66
Mediana: 51.5
Desvio Padrão: 24.77
Máximo: 96
Mínimo: 5


**Exercício 2: Operações com Matrizes**

Crie duas matrizes 3x3 de números inteiros aleatórios entre 1 e 10. Realize as operações de adição, subtração, multiplicação e divisão elemento por elemento entre as duas matrizes.

In [26]:
import numpy as np 

np.random.seed(2)

matriz1 = np.random.randint(1,11,(3,3))

matriz2 = np.random.randint(1,11,(3,3))
adic = matriz1 + matriz2
sub = matriz1 - matriz2
mult = matriz1 * matriz2
div = matriz1 / matriz2
dot = matriz1 @ matriz2

print(f'Matriz1:\n{matriz1}')
print(f'Matriz2:\n{matriz2}')

print(f"\nAdição:\n{adic}\nSubtração:\n{sub}\nMultiplicação Escalar:\n{mult}\nDivisão:\n{np.round(div, 2)}\nMultiplicação Algébrica:\n{dot} ")

Matriz1:
[[9 9 7]
 [3 9 8]
 [3 2 6]]
Matriz2:
[[5 5 6]
 [8 4 7]
 [5 4 8]]

Adição:
[[14 14 13]
 [11 13 15]
 [ 8  6 14]]
Subtração:
[[ 4  4  1]
 [-5  5  1]
 [-2 -2 -2]]
Multiplicação Escalar:
[[45 45 42]
 [24 36 56]
 [15  8 48]]
Divisão:
[[1.8  1.8  1.17]
 [0.38 2.25 1.14]
 [0.6  0.5  0.75]]
Multiplicação Algébrica:
[[152 109 173]
 [127  83 145]
 [ 61  47  80]] 


**Exercício 3: Operações de Agregação**

Crie uma matriz 4x4 de números inteiros aleatórios entre 1 e 20. Calcule e exiba a soma dos elementos para cada linha e para cada coluna.

In [ ]:
import numpy as np

np.random.seed(2)

Matrizinha = np.random.randint(1,21,(4,4))

print(f'Matriz:\n{Matrizinha}\n')

testesomatoria = np.sum(Matrizinha, axis=1) # 1 linha
testesomatoria2 = np.sum(Matrizinha, axis=0) # 0 Coluna

print(f'Somatoria Linhas: {testesomatoria}')
print(f'\nSomatoria Colunas:{testesomatoria2}')

Matriz:
[[ 9 16 14  9]
 [12 19 12  9]
 [ 8  3 18 12]
 [16  6  8  4]]

Somatoria Linhas: [48 52 41 34]

Somatoria Colunas:[45 44 52 34]


**Exercício 4: Filtragem de Valores**

Crie um array de 30 números inteiros aleatórios entre 0 e 50. Encontre e exiba todos os valores que são maiores que 25.

In [61]:
import numpy as np 

np.random.seed(1)

ary = np.random.randint(0,51,30)

print(ary)

print(f'\nArray dos Maiores que 25: {ary[ary>25]}')

[37 43 12  8  9 11  5 15  0 16  1 12  7 45  6 25 50 20 37 18 20 11 42 28
 29 14 50  4 23 23]

Array dos Maiores que 25: [37 43 45 50 37 42 28 29 50]


**Exercício 5: Criação e Manipulação de Arrays Multidimensionais**

Crie uma matriz 3x3x3 de números inteiros aleatórios entre 1 e 10. Calcule a soma total dos elementos e a soma cumulativa.

In [68]:
import numpy as np 

np.random.seed(21)

matriz3d = np.random.randint(1,11,(3,3,3))
somanormal = np.sum(matriz3d)
somacumulativa = np.cumsum(matriz3d).reshape(3, 3, 3)

print(f'Matriz 3D:\n {matriz3d}\n')
print(f'Soma Total: {somanormal}\n')
print(f'Soma Cumulativa:\n {somacumulativa}')

Matriz 3D:
 [[[10  9  5]
  [ 1  1  9]
  [ 4  3  2]]

 [[ 9 10  7]
  [ 1  5  7]
  [ 5  5  8]]

 [[ 9 10  6]
  [ 7  6  3]
  [ 7  3  9]]]

Soma Total: 161

Soma Cumulativa:
 [[[ 10  19  24]
  [ 25  26  35]
  [ 39  42  44]]

 [[ 53  63  70]
  [ 71  76  83]
  [ 88  93 101]]

 [[110 120 126]
  [133 139 142]
  [149 152 161]]]
